spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/simpleboard
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      hbm2ddl:
#        auto: update
      ddl-auto: create
    pro-perties:
      hibernate:
        format_sql: true
#        show_sql: true
logging:
  level:
    org.hibernate.SQL: debug
